#ifndef TABULARHELPER_GLOBAL_H
#define TABULARHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TABULARHELPER_LIBRARY)
#  define TABULARHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TABULARHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TABULARHELPER_GLOBAL_H
