language: cpp
compiler:
  - gcc
  - clang

before_install:
    - sudo apt-get install libqt4-dev qt4-qmake libpoppler-qt4-dev zlib1g-dev
script:
    - cd source
    - qmake texiteasy.pro
    - make -j 4
