language: cpp
compiler:
  - gcc
  - clang

before_install:
    - sudo apt-get update
    - sudo apt-get install libqt5-dev qt5-qmake libpoppler-qt5-dev zlib1g-dev
script:
    - cd source
    - qmake texiteasy.pro
    - make -j 4
