language: cpp
compiler:
  - gcc
  - clang

before_install:
    - sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools libpoppler-qt5-dev zlib1g-dev
script:
    - cd source
    - qmake texiteasy.pro
    - make -j 4
