language: cpp
compiler:
  - gcc
  - clang


before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev
script:
    - cd source
    - qmake texiteasy.pro -qt=qt5 -v
    - qmake texiteasy.pro -qt=qt5
    - make
